### ISSUE TITLE
OAuth2 always in status "authorizing"

### ISSUE THREAD

**Issue by onkelfu** [pckhib/node-red-contrib-homeconnect#3]
Hi!
I'm trying to get this node working. I configured client ID and client secret by using the data from the Home Connect application. Every time I click the button on the OAuth2 node, a website is coming up asking me for my home connect developer login and asking me to grant permissions to the application. At the end a white page just shows "OK". But from that point, the node keeps hanging in the status "authorizing".
Any suggestions what is going wrong?

Thank you a lot!

**Comment by pannlala** [comment]
I have the same issue.

**Comment by Jodameister** [comment]
This is caused by a change of the API in Authorization (https://developer.home-connect.com/docs/authorization/flow).
When the node request the token, in the body the param "redirect_uri" is missing: 

> client_id={client_id}&client_secret={client_secret}**&redirect_uri={redirect_uri}**&grant_type=authorization_code&code={code}

Easy Solution:
- Set a global var like cbUrl
- In the function getAuthorisationUrl, transfer the var "callbackUrl" to "cbUrl"
- in the function getTokens insert the redirect_uri with the cbUrl value

Greetings...

**Comment by pannlala** [comment]
Thank you for the help.
I don't know if I am stupid, blind or both. I cant find any files with that content. I have installed node-red-contrib-homeconnect from CLI. I have checked the folder and digged in all files without result.

**Comment by Jodameister** [comment]
[https://github.com/pckhib/node-red-contrib-homeconnect/blob/master/src/home-connect-auth.js](url)

Line 51

**Comment by Jodameister** [comment]
Line 33: Here you find the var callbackURL —> Store it in global var cbURL
Line 51: insert `"&redirect_uri=" + cbURL +`

**Comment by pannlala** [comment]
I still run in to trouble...
I am not a coder so my apologies if you think I'm a noob :)
responce: /oauth2/auth/callback?error=temporarily_unavailable&error_description=Internal+backend+service+currently+not+available

I have edited the file home-connect-auth.js
location: /usr/lib/node_modules/node-red-contrib-homeconnect/src/

declared a variable at row 1: var cbURL;
also tried with let cbURL;

this the line 33 code:
            let callbackUrl = protocol + '//' + hostname + (port ? ':' + port : '')
                + '/oauth2/auth/callback';

            var cbURL = callbackUrl;

line 51 code:

                body: 'client_id=' + n.client_id + 
                    '&client_secret=' + n.client_secret + 
                    '&redirect_uri=' + cbURL +
                    '&grant_type=authorization_code&code=' + authCode

**Comment by pannlala** [comment]
I sorted it out...
let cbURL; at line 4
var cbURL = callbackUrl; --> cbURL = callbackUrl at line 34...

Thank You for all help Jodameister!

**Comment by pckhib** [comment]
Callback URL was added in 8b8b634d
